# Playbook docs: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html
# Existing collections: https://docs.ansible.com/ansible/latest/collections/index.html
# Esp ansible.builtin: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/index.html
# Complex control flow: https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.htm

- name: Install packages
  hosts: all
  become: yes

  tasks:
  - name: gogogo
    dnf:
      name:
        - jq
        - httpd
      state: present
