# Playbook docs: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html
# Existing collections: https://docs.ansible.com/ansible/latest/collections/index.html
# Esp ansible.builtin: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/index.html
# Complex control flow: https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.htm

- name: Configure server
  hosts: all
  become: yes
  vars:
    username: "njormrod"
    supername: "njormrod"

  tasks:
  - name: Install packages
    dnf:
      name:
        - atop
        - clang
        - clang-tools-extra
        - git
        # - grpcio
        # - grpcio-tools
        - htop
        - httpd
        - jq
        - pip
        - tmux
        - zsh
      state: present

  - name: Install pips
    ansible.builtin.pip:
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
      name:
        #- ansible
        - flask
        #- jupyter

  - name: Ensure user exists
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    user:
      name: "{{ username }}"
      state: present
      shell: /bin/zsh

  - name: Grant user sudo power
    # https://docs.ansible.com/ansible/latest/collections/community/general/sudoers_module.html
    community.general.sudoers:
      user: "{{ username }}"
      name: "{{ username }}"
      commands: ALL
      runas: ALL

  - name: Set up .ssh dir
    file:
      path: "~{{ username }}/.ssh"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0700'

  - name: Copy ec2-user authorized_keys
    ignore_errors: yes
    copy:
      src: ~ec2-user/.ssh/authorized_keys
      remote_src: true
      dest: "~{{ username }}/.ssh/authorized_keys"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'

  - name: Copy github_ed25519
    copy:
      src: "~{{ supername }}/.ssh/{{ item.name }}"
      dest: "~{{ username }}/.ssh/{{ item.name }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: "{{ item.perm }}"
    with_items:
      - { name: "github_ed25519", perm: "0600" }
      - { name: "github_ed25519.pub", perm: "0644" }

- name: Configure server
  hosts: all
  vars:
    username: "njormrod"
  become: yes
  become_user: "{{ username }}"

  tasks:
  - name: Create directories
    file:
      path: "~/{{ item }}"
      state: directory
    with_items:
      - dev
      - jupyter
      - repos

  - name: Clone github repos
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    ansible.builtin.git:
      repo: "git@github.com:{{ item.maker }}/{{ item.name }}.git"
      dest: "~/{{ item.root }}/{{ item.name }}"
      accept_hostkey: yes
      key_file: "~/.ssh/github_ed25519"
    with_items:
      - { root: "dev", maker: "Gownta", name: "devenv" }
      - { root: "dev", maker: "Gownta", name: "starlang" }
      - { root: "dev", maker: "Gownta", name: "values" }
      - { root: "dev", maker: "Gownta", name: "hanabi" }
      - { root: "dev", maker: "Gownta", name: "farmwars" }

  - block:
    - name: Create dotfile save dir
      file:
        path: "~/dev/devenv/originals"
        state: directory

    - name: Save dotfiles
      ignore_errors: yes
      copy:
        src: "~/{{ item }}"
        remote_src: true
        dest: "~/dev/devenv/originals/{{ item | regex_replace('^\\.', '') }}"
        force: false
      with_items: "{{ existing_dotfiles }}"

    - name: Delete dotfiles
      file:
        path: "~/{{ item }}"
        state: absent
      with_items: "{{ existing_dotfiles }}"

    vars:
      existing_dotfiles:
        - .bashrc
        - .bash_logout
        - .bash_profile
        - .zshrc
        - .zprofile

  - name: Symlink dotfiles
    file:
      path: "~/{{ item.path }}"
      state: link
      src: "~/dev/devenv/{{ item.src }}"
    with_items:
      - { path: ".gitconfig", src: "configs/gitconfig" }
      - { path: ".tm_properties", src: "configs/textmate_properties" }
      - { path: ".tmux.conf", src: "configs/tmux.conf" }
      - { path: ".vimrc", src: "configs/vimrc" }
      - { path: ".zshenv", src: "configs/shell/env" }
      - { path: ".zshrc", src: "envs/aws_linux/zshrc" }

  - name: Create template dotfiles
    copy:
      dest: "~/{{ item.path }}"
      content: "{{ item.content }}"
      force: false
    with_items:
      - { path: ".secrets", content: "# Add lines to this file like export SECRET=ABC\n" }
      - { path: ".tmux.panes", content: "# ~\n# ~\n# ~\n# ~\n# ~\n" }

  - name: Create initial dotfiles
    copy:
      src: "~/dev/devenv/{{ item.src }}"
      remote_src: true
      dest: "~/{{ item.dest }}"
      force: false
    with_items:
      - { src: "configs/shell/prompt_vars_example", dest: ".prompt_vars" }
