export NJORMROD_DEVENV="$HOME/dev/devenv"

# Keep path entries unique.
# (N) prunes directories that do not exist.
# Do not prune edenfs dirs, since they might mount slowly.
typeset -U path PATH
path=(
  .
  $HOME/bin(N)
  $HOME/fbsource/users/nj/njormrod/bin
  $HOME/dev/devenv/bin(N)

  $HOME/dev/libai/bin(N)
  $HOME/dev/homebrew/bin(N)
  $HOME/dev/homebrew/sbin(N)
  $HOME/dev/bazel/bin(N)
  $HOME/.local/bin(N)
  $HOME/repos/dotfbsource/xplat/third-party/node/bin
  $HOME/repos/dotfbsource/xplat/third-party/yarn
  $HOME/dev/rust/cargo/bin(N)

  $path
)
export PATH

# Rust
# Instructions from https://www.rust-lang.org/tools/install are to run
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
export RUSTUP_HOME=$HOME/dev/rust/rustup
export CARGO_HOME=$HOME/dev/rust/cargo

# General
export EDITOR=/usr/bin/vim

# Common command controls
# man ls to see color options
export COLORTERM=truecolor
export CLICOLOR=1
export LSCOLORS=cxgxcxdxfxegedabagacad

# Cosmos
export COSMOS_BIN=/Users/njormrod/dev/starlang/cosmos/bin
