source "$NJORMROD_DEVENV/configs/shell/profile"
source "$NJORMROD_DEVENV/configs/shell/profile.zsh"
maybe_source "$HOME/.env_profile"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
